### ISSUE TITLE
Brakuje zależności w src/requirements.txt

### ISSUE THREAD

**Issue by illia-shkroba** [Grzegorz00/Solitune#38]
Próba uruchomienia REST API w nowym virtual environment kończy się błędami:

```text
ModuleNotFoundError: No module named 'sklearn'
ModuleNotFoundError: No module named 'pandas'
```

Brakuje też `fastapi` oraz `uvicorn` na liście zależności.

**Comment by Maciej-Ol** [comment]
Dodałem pandas, fastapi oraz uvicorn. Natomiast sklearn, a raczej scikit-learn==1.1.3, jest w pliku requirements.txt
