### ISSUE TITLE
Brak definicji `reorder_dataset_pipeline` w `solitune.dependencies.dependencies`

### ISSUE THREAD

**Issue by illia-shkroba** [Grzegorz00/Solitune#39]
Próba uruchomienia REST API kończy się błędem:

```text
ImportError: cannot import name 'reorder_dataset_pipeline' from 'solitune.dependencies.dependencies'
```

Rzeczywiście *src/solitune/dependencies/dependencies.py* nie zawiera implementacji `reorder_dataset_pipeline`.

**Comment by Maciej-Ol** [comment]
Dodany reorder_dataset_pipeline()
